// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aereal/github-ops/internal/cli/registersecret"
	"github.com/aereal/github-ops/internal/infrastructure/encryption"
	"github.com/aereal/github-ops/internal/infrastructure/github"
	"github.com/aereal/github-ops/internal/usecases"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp() *registersecret.App {
	client := github.ProvideGitHubClient()
	repositoryService := github.ProvideRepositoryService(client)
	encryptionService := encryption.ProvideEncryptionService()
	v := usecases.ProvideRegisterRepositorySecret(repositoryService, encryptionService)
	app := registersecret.ProvideApp(v)
	return app
}

// wire.go:

// InfrastructureSet provides all infrastructure dependencies
var InfrastructureSet = wire.NewSet(github.ProvideGitHubClient, github.ProvideRepositoryService, encryption.ProvideEncryptionService)

// UseCaseSet provides all use case dependencies
var UseCaseSet = wire.NewSet(usecases.ProvideRegisterRepositorySecret)

// AppSet provides application layer dependencies
var AppSet = wire.NewSet(registersecret.ProvideApp)
